"""Catalog of MaterialDesignIcons names used by the app.

Values are stored without the ``mdi.`` prefix; ``primitives.icon`` adds it.
"""

PLAY = "play"
STOP = "stop"
POWER = "power"
DELETE = "delete-outline"
REBOOT = "restart"
CLOUD = "cloud-upload-outline"
RECYCLE = "recycle"
LOG = "text-box-outline"
TAG = "tag-outline"
FLAG = "flag-outline"
KEY = "key-variant"
LAB = "flask-outline"
TUNNEL = "lan-connect"
DISCONNECT = "lan-disconnect"
COPY = "content-copy"
VERIFIED = "shield-check"
EXPAND = "chevron-down"
COLLAPSE = "chevron-up"
FILTER = "filter-variant"
SORT = "sort"
SELECT = "checkbox-multiple-marked-outline"
REFRESH = "refresh"
SETTINGS = "cog-outline"
CLOSE = "close"
CHECK = "check"
